---
title: "ABM Analysis"
output:
  html_document:
    df_print: paged
---

```{r import_data, echo = FALSE}

attempts <- read.csv('Number_of_Attempts.csv')
attempts$X = NULL
reattempts <- read.csv('Number_of_Reattempts.csv')
reattempts$X = NULL
errors <- read.csv('Number_of_Errors.csv')
errors$X = NULL

```

```{r calc, echo = FALSE}

step1_m <- mean(attempts$X0)
step1_sd <- sd(attempts$X0)

step2_m <- mean(attempts$X1)
step2_sd <- sd(attempts$X1)

step3_m <- mean(attempts$X2)
step3_sd <- sd(attempts$X2)

step4_m <- mean(attempts$X3)
step4_sd <- sd(attempts$X3)

step5_m <- mean(attempts$X4)
step5_sd <- sd(attempts$X4)

step6_m <- mean(attempts$X5)
step6_sd <- sd(attempts$X5)

step7_m <- mean(attempts$X6)
step7_sd <- sd(attempts$X6)

step8_m <- mean(attempts$X7)
step8_sd <- sd(attempts$X7)

step9_m <- mean(attempts$X8)
step9_sd <- sd(attempts$X8)

```

```{r graphs, echo = FALSE}

#plot(density(attempts$X0))
#plot(density(attempts$X1))
#plot(density(attempts$X2))
#plot(density(attempts$X3))
#plot(density(attempts$X4))
#plot(density(attempts$X5))
#plot(density(attempts$X6))
#plot(density(attempts$X7))
#plot(density(attempts$X8))

boxplot(attempts$X0, reattempts$X0, attempts$X1, reattempts$X1, attempts$X2, reattempts$X2, attempts$X3, reattempts$X3, attempts$X4, reattempts$X4, attempts$X5, reattempts$X5, attempts$X6, reattempts$X6, attempts$X7, reattempts$X7, attempts$X8, reattempts$X8,
        names = c('Step 1', 'Re 1', 'Step 2', 'Re 2', 'Step 3', 'Re 3', 'Step 4', 'Re 4', 'Step 5', 'Re 5', 'Step 6', 'Re 6', 'Step 7', 'Re 7', 'Step 8', 'Re 8', 'Step 9', 'Re 9'),
        #col = c('Brown', 'Red', 'Purple', 'Black', 'Green', 'Yellow', 'Orange', 'Pink', 'Blue'),
        ylab ='Number of Attempts',
        main = 'Number of Attempts for Each Step Over 100 Iterations')

boxplot(errors$X0, errors$X1, errors$X2, errors$X3, errors$X4, errors$X5, errors$X6, errors$X7, errors$X8, errors$X9, errors$X10, errors$X11, errors$X12, errors$X13, errors$X14, errors$X15, errors$X16, errors$X17, errors$X18, errors$X19, errors$X20, errors$X21, errors$X22, errors$X23, errors$X24, errors$X25, errors$X26, errors$X27, errors$X28, errors$X29, errors$X30, errors$X31, errors$X32, errors$X33, errors$X34, errors$X35,
        names = c(seq(36)),
        col = c('Brown', 'Red', 'Purple', 'Black', 'Green', 'Yellow', 'Orange', 'Pink', 'Blue'),
        ylab ='Number of Errors',
        main = 'Number of Errors for Each Step Over 50 Iterations')

```

``` {r Results, echo = FALSE}

errors <- read.csv('Number_of_Errors.csv')
errors$X = NULL

numit <- 0
zero_error <- 0
one_error <- 0
large_error <- 0
zef <- rep(0, 50)
oef <- rep(0, 50)
lef <- rep(0, 50)
errors$sum = rowSums(errors)
for (val in errors$sum) {
  if (val == 0) {
    zero_error <- zero_error + 1
  }
  if (val == 1) {
    one_error <- one_error + 1
  }
  if (val >= 2) {
    large_error <- large_error + 1
  }
  numit <- numit + 1
  zef[numit] <- zero_error/(numit)
  oef[numit] <- one_error/(numit)
  lef[numit] <- large_error/(numit)
}

# Plot graphs
plot(zef, type = "o", col="Orange", pch=15, ylim=c(0,1.5), main = "Error Fractions over 50 Iterations", xlab = "Number of Iterations", ylab = "Error Fractions")
lines(oef, type = "o", col="Green", pch=15)
lines(lef, type = "o", col="Blue", pch=15)
legend('topright', c('0 error fraction', '1 error fraction', '>=2 error fraction'), col=c('Orange', 'Green', 'Blue'), pch = c(15, 15, 15))

```